{{- if .Values.service.externalEndpointEnabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.codenow.componentRuntimeName }}-service
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  -  istio-system/public-gateway
  hosts:
    - {{ .Values.codenow.componentRuntimeName }}-{{ .Release.Namespace }}.{{ .Values.codenow.domainName }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.codenow.componentRuntimeName }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
{{- end }}